### ISSUE TITLE
Question about channel model

### ISSUE THREAD

**Issue by zyy341** [emilbjornson/cell-free-book#2]
Dear Professor Emil Björnson，
The channel H_{kl} in the system characterizes large-scale and small-scale fading between the l-th AP and the k-th UE.
In the code, the  large-scale fading is defined as gainOverNoisedB, shown as follow: 
https://github.com/emilbjornson/cell-free-book/blob/0bf414646c5e33c20ba37636a7fc58ffa46070ac/code/section5_figure4a_6a.m#L71

While in channel estimation
https://github.com/emilbjornson/cell-free-book/blob/0bf414646c5e33c20ba37636a7fc58ffa46070ac/code/section5_figure4a_6a.m#L75

It generates spatial correlated Rayleigh fading channel.  And then, implement MMSE channel estimation on the it. In other words, it estimates the small-scale fading channel.
https://github.com/emilbjornson/cell-free-book/blob/0bf414646c5e33c20ba37636a7fc58ffa46070ac/code/functionChannelEstimates.m#L52-L66

As we know,  the pilot signal tau_{tk} sent from the k-th UE to l-th AP will experience large-scale fading. But it only estimated the small-scale fading channel. So, the signal distortions caused by large-scale fading appear to be ignored.  

In cell-free-book section 4.4 said in practical systems, the APs are periodically broadcasting synchronization signals to convey basic access information. The channel gains(large-scale)can be measured based on these signals. 

My question is that before AP does signal processing(such as channel estimation or receive combining), because of the known channel gains, APs will first compensate for signal distortions due to large-scale fading? Therefore, when AP does signal processing, we only need to focus on signal distortions due to small-scale fading? Such as estimates the correlated Rayleigh fading channel and  implement receive combine based on the correlated Rayleigh fading channel.

Thank you for your time and I look forward to hearing from you soon!
Best regards.

**Comment by emilbjornson** [comment]
Hi!

If you have questions related to the content of the book, it is more convenient if you send an email to the authors than raising an issue on GitHub. In that way, I can more easily keep track of questions that are submitted.

The separation between “small-scale” and “large-scale” fading is made in textbooks to explain that some physical phenomena create fast channel changes and some create slower channel changes. However, it just two flavors of the same thing. Both concepts are described by h_kl. The large-scale fading determines its average gain while the small-scale fading creates variations around it.

In this book, the small-scale fading is described by a complex Gaussian distribution, while the large-scale fading determines the variance of the distribution. In the code, we are first computing the variance based on the user location in generateSetup (actually an entire covariance/correlation matrix per user) and then we use it when generating the small-scale fading realizations in a row like this:
H((l-1)*N+1:l*N,:,k) = sqrt(0.5)*Rsqrt*H((l-1)*N+1:l*N,:,k); 
There is no extra signal processing related to compensating for large-scale fading. It is already done in the estimation, combining, and precoding.

Best regards

Emil Björnson

**Comment by zyy341** [comment]
> 
many thanks for your reply
